# Generated by Django 6.1.1 on 2026-10-01 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('metrics', models.JSONField(default=dict)),
                ('published', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ScamFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_fingerprint', models.TextField()),
                ('representative_text', models.TextField(blank=True)),
                ('category', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('new', 'New / unverified'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected (not a scam)')], default='new', max_length=10)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_example', models.BooleanField(default=False, help_text='Seed example, clearly marked.')),
            ],
            options={
                'verbose_name_plural': 'scam families',
                'ordering': ['-report_count', '-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redacted_text', models.TextField()),
                ('fingerprint', models.TextField()),
                ('channel', models.CharField(blank=True, max_length=30)),
                ('claimed_category', models.CharField(blank=True, max_length=40)),
                ('device_hash', models.CharField(db_index=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.scamfamily')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_hash', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('scam', 'This is a scam'), ('fine', 'This is fine')], max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.scamfamily')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device_hash', 'family'), name='one_vote_per_device_per_family')],
            },
        ),
    ]
